language: python
python:
  - "3.3"
install:
  - "apt-get install python-mock"
  - "pip install -r requirements.txt"
script:
  - "PYTHONPATH=. py.test"       # run unit tests
  - "python setup.py install"    # test install
  - "sphinx-build -W docs html"     # test building docs
